# -*- coding: utf-8 -*-
"""skin_classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PX3IGDz0M7FAsmqSbQCg5URGUrY5AsL5
"""

import matplotlib.pyplot as plt
from sklearn import svm
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np

dataset = pd.read_csv("Skin_Nonskin(mod).csv")

X=dataset[['AA','BB','CC']]



Y=dataset['CLASS']

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.25)

plt.scatter(X['AA'],X['BB'],X['CC'], c=Y)
plt.show()

# Create a linear SVM classifier
clf = svm.SVC(kernel='linear')

# Train classifier
clf.fit(x_train,y_train)

clf_predictions = clf.predict(x_test)

RMSE=clf.score(x_test, y_test)

print("Accuracy: {}%".format(clf.score(x_test, y_test) * 100 ))

print("RMSE: ", RMSE)